{application,explane,
             [{description,[]},
              {vsn,"0.1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{explane_app,[]}},
              {env,[{udp_receive_port,20001},{udp_send_port,20000}]},
              {modules,[explane,explane_app,explane_packet,explane_server,
                        explane_sup,reloader]}]}.
