{application,explane,
             [{description,[]},
              {vsn,"0.1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{explane_app,[]}},
              {env,[]},
              {modules,[explane,explane_app,explane_server,explane_sup,
                        reloader]}]}.
